### ISSUE TITLE
无法查看Html代码

### ISSUE THREAD

**Issue by hicyrus** [mycolorway/simditor-html#1]
点击查看html代码的按钮，按钮会变色，但是无法查看Html代码？不知到是不是bug!

**Comment by farthinker** [comment]
@hicyrus 仓库里的demo没有这个问题，麻烦你确认一下引用的脚本是否正确，console里是否有相关报错

**Comment by hicyrus** [comment]
谢谢找到问题了js都引入了，没有引入simditor-html.css导致的！

**Comment by shiny** [comment]
我也遇到了同样的问题，建议放一个 demo 就知道是怎么回事了。
