### ISSUE TITLE
html编辑模式时，不能插入iframe和embed，

### ISSUE THREAD

**Issue by jun1st** [mycolorway/simditor-html#5]
这个应该和simditor.js文件中的，allowedTags和cleanNode中的过滤有关系，

**Comment by farthinker** [comment]
为了保证输出标准干净的HTML，simditor采用了白名单机制来过滤编辑器里的内容。相关文档：http://simditor.tower.im/docs/doc-config.html#anchor-allowedTags

你可以通过配置allowedTags、allowedAttributes来支持iframe和embed标签
